### ISSUE TITLE
App crashes when clicking on the "Homepage" button

### ISSUE THREAD

**Issue by DavidIQ** [AntonyCorbett/JWLMerge#55]
**Describe the bug**
When clicking on the _Homepage_ button the app immediately closes.

**To Reproduce**
1. Open app
2. Click on _Homepage_ button
3. See error:

```
2021-10-11 20:09:59.284 -04:00 [INF] ==== Launched ====
2021-10-11 20:09:59.327 -04:00 [INF] Version 2.0.0.5
2021-10-11 20:10:09.256 -04:00 [FTL] Unhandled exception
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at JWLMerge.ViewModel.MainViewModel.LaunchHomepage()
   at Microsoft.Toolkit.Mvvm.Input.RelayCommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
```

**Expected behavior**
Default browser opens on the preset web URL.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Windows version 11

**Comment by DavidIQ** [comment]
I'm assuming that this is happening because, for some reason, the `HOMEPAGE` value being used [here](https://github.com/AntonyCorbett/JWLMerge/blob/master/JWLMerge/ViewModel/MainViewModel.cs#L538) isn't there.
