### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by Chiriat** [AntonyCorbett/JWLMerge#61]
Hi bro Anthony,
i am trying to export bible notes to excel and i always get this error message.

Thanks for your help

System.ArgumentOutOfRangeException: Cells can hold a maximum of 32,767 characters. (Parameter 'cellValue')
   at ClosedXML.Excel.XLCell.SetInternalCellValueString(String cellValue, Boolean validate, Boolean parseToCachedValue)
   at ClosedXML.Excel.XLCell.SetValue[T](T value, Boolean setTableHeader)
   at ClosedXML.Excel.XLCell.SetValue[T](T value)
   at JWLMerge.ExcelServices.ExcelService.SetCellStringValue(IXLWorksheet worksheet, Int32 row, Int32 col, String value)
   at JWLMerge.ExcelServices.ExcelService.AppendToBibleNotesFile(String excelFilePath, IReadOnlyCollection`1 notes, Int32 startRow, String backupFilePath)
   at JWLMerge.BackupFileServices.BackupFileService.ExportBibleNotesToExcel(BackupFile backupFile, String bibleNotesExportFilePath, IExcelService excelService)
   at JWLMerge.ViewModel.MainViewModel.<>c__DisplayClass84_0.<ExportBibleNotesAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at JWLMerge.ViewModel.MainViewModel.ExportBibleNotesAsync(String filePath)

**Comment by AntonyCorbett** [comment]
@Chiriat Hi. Yes, I saw your crash in the App Center dashboard. I have fixed this by truncating any notes that are too long and then displaying a notification. At least the export continues. The code is already in the repo, but I have not published a new release yet. Look out for v2.0.0.10+ which I should get done at the weekend. Regards, Antony

**Comment by AntonyCorbett** [comment]
@Chiriat v2.0.0.10 is now available. Since long notes are now truncated, the export should work but of course the excel file will contain truncated notes!

**Comment by Chiriat** [comment]
thanks a lot
